--   Fichier de controle du chargement dans la table RC_HISTO_DOCUMENT --
-- (DIRECT=TRUE) UNRECOVERABLE
-- (DIRECT=FALSE)
--INFILE RC_HISTO_DOCUMENT.dat
OPTIONS (SKIP=1, ERRORS=100) 
LOAD DATA
APPEND INTO TABLE RC_HISTO_DOCUMENT 
FIELDS TERMINATED BY '|'
(ID SEQUENCE (MAX,1),
 INTERROGATION_ID,
 FILE_NAME,
 ext_fname FILLER CHAR(256),
 DOCUMENT LOBFILE(ext_fname) TERMINATED BY EOF)

