--   Fichier de controle du chargement dans la table RC_HISTO_COMMENT --
-- (DIRECT=TRUE) UNRECOVERABLE
-- (DIRECT=FALSE)
--INFILE RC_HISTO_COMMENT.dat
OPTIONS (SKIP=1, ERRORS=100) 
LOAD DATA
APPEND INTO TABLE RC_HISTO_COMMENT 
FIELDS TERMINATED BY '|'
(ID SEQUENCE (MAX,1),
 INTERROGATION_ID,
 COMMENT_DATE DATE "DD/MM/YYYY HH24:MI",
 USER_NAME,
 COMMENTS CHAR(12000))

