--   Fichier de contrôle du chargement dans la table RC_HISTO_FICHE --
-- (DIRECT=TRUE) UNRECOVERABLE
-- (DIRECT=FALSE)
--INFILE RC_HISTO_INTERROGATION.dat
OPTIONS (SKIP=1, ERRORS=100) 
LOAD DATA
APPEND INTO TABLE RC_HISTO_INTERROGATION 
FIELDS TERMINATED BY '|'                                                            
(
STATUS,
INTERROGATION_TYPE "DECODE(:INTERROGATION_TYPE, 'SANCTIONS', 'SANCTION', :INTERROGATION_TYPE)",
INTERROGATION_REF,
INTERNE_REF,
RECOVERY_DATE DATE "DD/MM/YYYY HH24:MI",
RECOVERY_DONE,
RECEPTION_DATE DATE "DD/MM/YYYY HH24:MI",
CANCELLATION_DATE DATE "DD/MM/YYYY HH24:MI",
MESSAGE_TYPE,
IN_OUT,
QUESTIONNED_BANK,
ISSUER_BANK,
AMOUNT "REPLACE(REPLACE(TRIM(SUBSTR(:AMOUNT, 0, LENGTH(:AMOUNT) - 3)), ',', '.'), ' ', '')",
CURRENCY,
BUSINESS_MANAGER,
INTERROGATION_FATE,
CHAMP_DATE FILLER,
RELEVANT_ANSWER,
ANSWER_REFERENCE,
COMMENTAIRE FILLER CHAR(12000),
INTERROGATION_CRITERIA_FIRCO,
INTERROGATION_CRITERIA_GAFI,
INTERROGATION_DATE DATE "DD/MM/YYYY HH24:MI",
HITS,
ID,
CREATION_DATE,
DATE_MODIF FILLER,
TYPE_ELEM FILLER,
CHEMIN FILLER
)

